### ISSUE TITLE
JS interoperation problem with OpenUI5

### ISSUE THREAD

**Issue by dhoehmann** [ceylon/ceylon-js#615]
This code:

      dynamic {
		dynamic label = sap.m.Label();
		label.setText("Hallo Welt!");
		label.placeAt("content2");
	}

causes compilation error: `GenerateJsVisitor caused an exception visiting QualifiedTypeExpression node: java.lang.NullPointerException at unknown	run.ceylon	/Mayflower/source/scratchpad	line 123	Ceylon Backend Error`

changing to:

      dynamic {
		dynamic label = sap.m.\iLabel();
		label.setText("Hallo Welt!");
		label.placeAt("content2");
	}

compiles but leads to runtime error: Uncaught Error: Cannot instantiate object: "new" is missing!

**Comment by chochos** [comment]
So I guess it should compile to `new sap.m.Label()`?

**Comment by dhoehmann** [comment]
Yes that's exactly what is needed for OpenUI5

**Comment by chochos** [comment]
I just tested this and the correct code is generated. What version are you using?

**Comment by dhoehmann** [comment]
Sorry, should have included that info. I'm working on 1.1. So it's probably already fixed in 1.2

**Comment by chochos** [comment]
yes the fix will be available in 1.2
